### ISSUE TITLE
ShortStack 4.0.0 does not install in ubuntu 22.04

### ISSUE THREAD

**Issue by cche** [MikeAxtell/ShortStack#122] opened 2023-03-27 15:02 UTC
Hi,
I have problems installing the latest version of ShortStack.

conda install -n shortstack shortstack
installs version 3.8.5

When I try to install with
conda install -n shortstack shortstack=4.0.0

It does not install due to incompatibility issues:
The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.36=0
  - feature:|@/linux-64::__glibc==2.36=0
  - bedtools -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - biopython -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - cutadapt -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - numpy -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - python[version='>=3.10.8'] -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - viennarna=2 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.36

Does anybody know how to solve this problem?

Thanks
Cristian

**Comment by forrestbao** [comment] 2023-04-08 06:15
I have the same issue too!

**Comment by AlineMuyle** [comment] 2023-04-11 08:24
We're having the same issue

**Comment by cche** [comment] 2023-04-11 11:27
I've tested the installation on a ubuntu 22.10 machine which is up to date on all packages, ubuntu WSL 22.04 and on a Rocky linux machine, also up to date, and it does not install.

When trying the installation by hand, conda installs bowtie 1.0 and when I try to force the installation of bowtie 1.3 it gives a similar error as cited before (problem with gcc).

In the meantime, we did the analysis with version 3.8.5, but I would really like to be able to do future analyses with version 4.0.0 to be able to use all the latest additions and reduce calculation time.

Could you share your machine configuration to compare to what I'm using?
Thanks!

**Comment by MikeAxtell** [comment] 2023-04-11 12:09
Hi everyone, sorry about these problems. We are unable to reproduce them here, so I am groping in the dark for solutions. My primary testing device is one of Penn State's HPC clusters, which is running Red Hat Enterprise Linux 8.7. We have also tested successfully on various Mac laptops running both Intel and Silicon chipsets. None of us have encountered this error on any of our machines to date.

I believe this is a `conda` configuration issue of some kind. Here are some ideas to try, based on googling similar issues from other similar`conda` malfunctions:

- update `conda`: `conda update conda`
- Ensure that the `conda` config is correctly set to use bioconda. Specifically, per the instructions at <https://bioconda.github.io> execute the following 4 commands *in this order*. This sets conda-forge as the highest priority channel, and defaults as the lowest, and ensures that these priorities are strictly followed when resolving dependencies:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```
- After performing the above, verify that `~/.condarc` has the correct configuration. Here's mine:
```
$ cat ~/.condarc
channels:
  - conda-forge
  - bioconda
  - defaults
channel_priority: strict
repodata_fns:
  - repodata.json
```
If your `condarc` has additional channels, I suggest deleting them from the config.
- Do not attempt to install into the `base` conda environment. 
- Try creating and activating an empty environment before installing:
```
conda create --name ShortStack4
conda activate ShortStack4
conda install shortstack
```
- If you are running Anaconda, consider nuking it and just installing Miniconda instead in a clean installation. Anaconda is pretty bloated and may be doing strange things to the operation of the `conda` command.

**Comment by MikeAxtell** [comment] 2023-04-11 15:40
I asked chatGPT and here's what it said:

This error message is indicating that the package you are trying to install has dependencies that require a specific version of the GNU C Library (glibc) that is not compatible with the version installed on your system.

One possible solution is to update your glibc to the required version. However, this is not recommended as it can potentially break other programs that rely on the current version of glibc.

An alternative solution is to create a new environment with a compatible version of glibc and install the package in that environment. To do this, follow these steps:

1. Create a new conda environment with a compatible version of glibc. For example, if the package you are trying to install requires glibc version 2.17, you can create a new environment with that version using the following command:

`conda create --name myenv linux-64::__glibc==2.17`

2. Activate the new environment:

`conda activate myenv`

3. Install the package in the new environment:

`conda install package_name`

This should resolve the dependency issue and allow you to install the package in a separate environment.

**Comment by cche** [comment] 2023-04-12 07:34
This is solved for me!

I think my problem was a faulty configuration of my .condarc because I had problems a long time ago with another package. Maybe this was the problem? Somehow, declaring the channels on the command line didn't do the trick for me earlier.

Anyhow, after following the bioconda setup from scratch, by removing .condarc first, it now installs. I still have to use shortstack=4.0.0 otherwise it will try to install version 3.8.5, but that is no problem. 

Thanks!

**Comment by somnya** [comment] 2023-04-12 11:37
Hello! 

I also did what [you suggested about the .condarc file ](https://github.com/MikeAxtell/ShortStack/issues/122#issuecomment-1503214553)

Now it is working! Thank you so much :)

**Comment by MikeAxtell** [comment] 2023-04-19 18:02
- note to self - Should add this to the FAQ of the README ..

**Comment by MikeAxtell** [comment] 2023-04-20 18:04
As of [8adb7b4](https://github.com/MikeAxtell/ShortStack/commit/8adb7b46863dcfda7e5b0270aa7656f5fdebb3f7) the README contains the fixes to these apparently common conda issues. So, I am closing this issue.

**Closed by MikeAxtell** 2023-04-20 18:04 UTC
Labels: question
